### ISSUE TITLE
Forming of Multiple layers through embedded link does not work 

### ISSUE THREAD

**Issue by Rulesroxx** [mitre-attack/attack-navigator#624]
While loading a JSON which has multiple layers through embedded links in the URL leads to error and doesn't load the navigator matrix. Kindly provide a fix for the same. The error is given below. 
```
main.e4d9a7b63e309eec.js:1 Error: Error: 'undefined' (v14) is an invalid domain.
    at Object.<anonymous> (main.e4d9a7b63e309eec.js:1:3279929)
    at Generator.next (<anonymous>)
    at qB (main.e4d9a7b63e309eec.js:1:2518190)
    at a (main.e4d9a7b63e309eec.js:1:2518393)
    at gt.invoke (polyfills.37da30a5d917820e.js:1:8940)
    at Object.onInvoke (main.e4d9a7b63e309eec.js:1:1545998)
    at gt.invoke (polyfills.37da30a5d917820e.js:1:8878)
    at tt.run (polyfills.37da30a5d917820e.js:1:4239)
    at polyfills.37da30a5d917820e.js:1:19375
    at gt.invokeTask (polyfills.37da30a5d917820e.js:1:9563)
 ```

**Comment by clemiller** [comment]
Thank you for reporting this bug! A fix for this issue is staged on `develop` and will be included in the upcoming release.
